<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MUM-LAP-1579" failures="1" tests="4" name="LaunchWebsiteWithTestNGAssertion" time="13.129" errors="0" timestamp="2023-02-27T16:22:23 IST" skipped="0">
  <testcase classname="LaunchWebsiteWithTestNGAssertion" name="initialMethod" time="0.008"/>
  <system-out>
    <![CDATA[TestNG started]]>
  </system-out>
  <testcase classname="LaunchWebsiteWithTestNGAssertion" name="skipTest" time="0.001"/>
  <system-out/>
  <testcase classname="LaunchWebsiteWithTestNGAssertion" name="LaunchEdgeDriver" time="8.214">
    <failure message="The following asserts failed:
	expected [Testing Demo] but found [Testing Demo Site | Practice Website For Automation - Global SQA]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Testing Demo] but found [Testing Demo Site | Practice Website For Automation - Global SQA]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at LaunchWebsiteWithTestNGAssertion.LaunchEdgeDriver(LaunchWebsiteWithTestNGAssertion.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LaunchEdgeDriver -->
  <system-out/>
  <testcase classname="LaunchWebsiteWithTestNGAssertion" name="Method2" time="4.906"/>
  <system-out/>
</testsuite> <!-- LaunchWebsiteWithTestNGAssertion -->
